url: https://ippyfil.pt
baseurl: /
# url: https://ippyfil.github.io
# baseurl: /Ippyfil-Website/
#url: https://ippyfil-website.vercel.app/
#index: pt

# Site settings
title: Cerveja Artesanal Craft Beer Ippyfil
email: ippyfil@posteo.net
description: "Cerveja Artesnal Ippyfil, em Lisboa. Craft Beer in Lisbon Ippyfil. Queremos-te reconectar à natureza através das nossas cervejas"


# Team names, titles and social links
people:

- name: Filipe Matos
  pic: filipe
  en:
    position: Head Brewer
    description: Astrophycicist, began brewing beer while studying in Amsterdam. Passioin for craft beer for several years.
  pt:
    position: Cervejeiro
    description: Astrofísico de formação, começou a produzir em Amsterdão enquanto estudava. Apaixonado pela cerveja artesanal há vários anos, é entusiasta da permacultura e agricultura regenerativa e encontra na Ippyfil uma forma de ligar os dois, a paixão por regenerar ecossistemas plantando futuros ingredientes para a cerveja.
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Inês Eugénio
  pic: ines
  en:
    position: Head Brewer
    description: working on
  pt:
    position: Cervejeira
    description: Engenheira biológica, estudou no instituto superior técnico, onde aprendeu a arte cervejeira. Tem um grande gosto pelas inovações na area industrial mas um carinho especial pelo artesanal. Gosta de viver, de se divertir e enfrenta qualquer desafio de forma positiva e sorridente.
#  pt:
# -  name: Filipe Matos
#    pic: 1
#    position: Cervejeiro
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

#  - name: Inês Eugénio
#    pic: ines
#    position: Cervejeira

  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/cervejaippyfil/
  - title: facebook
    url: https://www.facebook.com/ippyfil/
  - title: untappd
    url: https://www.untappd.com/ippyfil/

contact:
  - address: +351 919237206
    icon: phone
  - address: Rua David Lopes 23 A-B
    icon: map-marker
  - address: ippyfil@posteo.net
    icon: at

# Postal address (add as many lines as necessary)
address:
  - line: Rua David Lopes 23 A-B
  - line: Lisboa 

# Build settings
markdown: kramdown
permalink: pretty

collections:
  sliders:
    output: true
  shop-items:
    output: true
