url: https://ippyfil.github.io
baseurl: /Ippyfil-Website/
index: pt

# Site settings
title: Ippyfil
email: ippyfil@posteo.net
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:

- name: Filipe Matos
  pic: filipe
  en:
    position: Head Brewer
  pt:
    position: Cervejeiro
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

- name: Inês Eugénio
  pic: ines
  en:
    position: Head Brewer
  pt:
    position: Cervejeiro
#  pt:
# -  name: Filipe Matos
#    pic: 1
#    position: Cervejeiro
  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: stack-overflow
  #    url: #

#  - name: Inês Eugénio
#    pic: ines
#    position: Cervejeira

  #social:
  #  - title: twitter
  #    url: #
  #  - title: facebook
  #    url: #
  #  - title: linkedin
  #    url: #
#- name: Diana Petersen
#  pic: 3
#  position: Lead Developer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/ippyfil_brewery/
  - title: facebook
    url: https://www.facebook.com/ippyfil/

contact:
  - address: +351 919237206
    icon: phone
  - address: Rua David Lopes 23 A-B
    icon: map-marker
  - address: ippyfil@posteo.net
    icon: at

# Postal address (add as many lines as necessary)
address:
  - line: Rua David Lopes 23 A-B
  - line: Lisboa 

# Build settings
markdown: kramdown
permalink: pretty
